using System.ComponentModel.DataAnnotations;

namespace AutomatedCryptoTradingPlatform.Core.Dtos.Requests;

/// <summary>
/// DTO for wallet login request
/// </summary>
public class WalletLoginDto
{
    /// <summary>
    /// Wallet address (e.g., 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1)
    /// </summary>
    [Required(ErrorMessage = "Wallet address is required")]
    public string WalletAddress { get; set; } = string.Empty;

    /// <summary>
    /// Signature generated by wallet after signing the nonce
    /// </summary>
    [Required(ErrorMessage = "Signature is required")]
    public string Signature { get; set; } = string.Empty;

    /// <summary>
    /// Nonce that was signed (from GET /wallet/nonce)
    /// </summary>
    [Required(ErrorMessage = "Nonce is required")]
    public string Nonce { get; set; } = string.Empty;

    /// <summary>
    /// Optional wallet type (MetaMask, Phantom, etc.)
    /// </summary>
    public string? WalletType { get; set; }
}
